In [4]:
import sys
print(sys.executable)

/home/user/miniconda3/envs/athero-vae/bin/python

In [8]:
import pandas as pd

expr = pd.read_csv("/data/athero-vae/data/processed/expression_matrix.csv", index_col=0)
meth = pd.read_csv("/data/athero-vae/data/processed/methylation_matrix.csv", index_col=0)

print(expr.shape)
print(meth.shape)

(47278, 1202)
(485577, 2404)

In [11]:
meth.head()

,100001.Mvalue,100001.detectionPval,100002.Mvalue,100002.detectionPval,100003.Mvalue,100003.detectionPval,100004.Mvalue,100004.detectionPval,100005.Mvalue,100005.detectionPval,...,101260.Mvalue,101260.detectionPval,101261.Mvalue,101261.detectionPval,101262.Mvalue,101262.detectionPval,101263.Mvalue,101263.detectionPval,101264.Mvalue,101264.detectionPval
ID_REF,,,,,,,,,,,,,,,,,,,,,
cg00000029,-0.248280,0.0,-0.020392,0.0,-0.373721,0.0,-0.237185,0.0,0.284723,0.0,...,0.092756,0.0,-0.570741,0.0,-0.390567,0.0,0.162912,0.0,-0.273485,0.0
cg00000108,3.516344,0.0,3.856286,0.0,4.239439,0.0,3.519516,0.0,3.880296,0.0,...,3.873464,0.0,3.284091,0.0,3.561364,0.0,4.042576,0.0,3.319701,0.0
cg00000109,2.752625,0.0,3.267494,0.0,2.992055,0.0,2.926529,0.0,2.868053,0.0,...,2.877356,0.0,2.353765,0.0,3.144560,0.0,2.777298,0.0,3.468839,0.0
cg00000165,-2.030849,0.0,-1.462111,0.0,-1.464236,0.0,-1.569228,0.0,-1.719939,0.0,...,-1.019750,0.0,-1.782947,0.0,-1.637511,0.0,-2.138793,0.0,-1.970228,0.0
cg00000236,1.069549,0.0,1.146412,0.0,1.340683,0.0,0.962154,0.0,1.104444,0.0,...,1.057207,0.0,1.667247,0.0,1.240644,0.0,0.973126,0.0,1.080876,0.0

In [10]:
expr.head()

,GSM1352002,GSM1352003,GSM1352004,GSM1352005,GSM1352006,GSM1352007,GSM1352008,GSM1352009,GSM1352010,GSM1352011,...,GSM1353194,GSM1353195,GSM1353196,GSM1353197,GSM1353198,GSM1353199,GSM1353200,GSM1353201,GSM1353202,GSM1353203
ID_REF,,,,,,,,,,,,,,,,,,,,,
ILMN_1762337,5.136625,5.089840,5.268244,5.247811,4.984297,5.099019,5.401281,5.497121,5.290908,5.743592,...,5.189426,5.095456,5.250572,5.396671,5.116644,5.357195,5.142840,4.967980,5.166105,5.199865
ILMN_2055271,5.878106,6.867448,6.085611,6.116644,5.960724,7.124572,6.645861,5.981317,6.025220,6.999142,...,5.858105,5.529138,5.762097,6.076816,6.001335,7.164932,5.489062,6.491508,6.892653,5.150740
ILMN_1736007,5.184706,5.258854,4.954293,5.115758,5.122904,5.210427,5.144561,4.999533,4.981587,5.014846,...,4.978505,5.151428,5.232020,5.116558,5.545990,5.135728,5.016644,5.230082,4.971681,5.303597
ILMN_2383229,5.415968,4.915011,5.042886,5.190248,4.900996,5.209508,4.948399,5.052756,5.223667,5.167986,...,5.208470,5.018134,5.015709,5.167865,4.985861,5.104405,4.962391,5.180023,5.113188,4.993768
ILMN_1806310,5.079431,4.985693,5.116782,5.226024,5.183386,4.895404,5.201298,5.025883,5.049895,4.962199,...,5.445138,4.973678,5.043262,5.104420,5.037863,4.983197,5.067597,5.337265,4.987283,5.082369

In [12]:
meth = meth.filter(regex="Mvalue")

In [13]:
print(meth.shape)

(485577, 1202)

In [14]:
meth.columns = meth.columns.str.replace(".Mvalue", "", regex=False)

In [15]:
print(meth.columns[:10])
print(expr.columns[:10])

Index(['100001', '100002', '100003', '100004', '100005', '100006', '100007',
       '100008', '100009', '100010'],
      dtype='object')
Index(['GSM1352002', 'GSM1352003', 'GSM1352004', 'GSM1352005', 'GSM1352006',
       'GSM1352007', 'GSM1352008', 'GSM1352009', 'GSM1352010', 'GSM1352011'],
      dtype='object')

In [16]:
print(expr.columns[:10])
print(meth.columns[:10])

Index(['GSM1352002', 'GSM1352003', 'GSM1352004', 'GSM1352005', 'GSM1352006',
       'GSM1352007', 'GSM1352008', 'GSM1352009', 'GSM1352010', 'GSM1352011'],
      dtype='object')
Index(['100001', '100002', '100003', '100004', '100005', '100006', '100007',
       '100008', '100009', '100010'],
      dtype='object')

In [17]:
import GEOparse

gse = GEOparse.get_GEO("GSE56045", destdir="data/raw")

mapping = {}

for gsm_id, gsm in gse.gsms.items():
    
    title = gsm.metadata['title'][0]
    
    subject_id = title.split("_")[0]   # "100001_peripheral_CD14"
    
    mapping[gsm_id] = subject_id

16-Mar-2026 13:05:32 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE56nnn/GSE56045/soft/GSE56045_family.soft.gz to data/raw/GSE56045_family.soft.gz
100%|██████████| 791M/791M [01:00<00:00, 13.8MB/s]
16-Mar-2026 13:06:34 DEBUG downloader - Size validation passed
16-Mar-2026 13:06:34 DEBUG downloader - Moving /tmp/tmp_521r_4d to /data/athero-vae/notebooks/data/raw/GSE56045_family.soft.gz
16-Mar-2026 13:06:34 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE56nnn/GSE56045/soft/GSE56045_family.soft.gz
16-Mar-2026 13:06:35 INFO GEOparse - Parsing data/raw/GSE56045_family.soft.gz:
16-Mar-2026 13:06:35 DEBUG GEOparse - DATABASE: GeoMiame
16-Mar-2026 13:06:35 DEBUG GEOparse - SERIES: GSE56045
16-Mar-2026 13:06:35 DEBUG GEOparse - PLATFORM: GPL10558
16-Mar-2026 13:06:35 DEBUG GEOparse - SAMPLE: GSM1352002
16-Mar-2026 13:06:35 DEBUG GEOparse - SAMPLE: GSM1352003
16-Mar-2026 13:06:35 DEBUG GEOparse - SAMPLE: GSM1352004
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352005
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352006
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352007
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352008
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352009
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352010
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352011
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352012
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352013
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352014
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352015
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352016
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352017
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352018
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352019
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352020
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352021
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352022
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352023
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352024
16-Mar-2026 13:06:36 DEBUG GEOparse - SAMPLE: GSM1352025
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352026
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352027
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352028
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352029
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352030
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352031
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352032
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352033
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352034
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352035
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352036
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352037
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352038
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352039
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352040
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352041
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352042
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352043
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352044
16-Mar-2026 13:06:37 DEBUG GEOparse - SAMPLE: GSM1352045
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352046
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352047
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352048
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352049
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352050
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352051
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352052
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352053
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352054
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352055
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352056
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352057
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352058
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352059
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352060
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352061
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352062
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352063
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352064
16-Mar-2026 13:06:38 DEBUG GEOparse - SAMPLE: GSM1352065
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352066
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352067
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352068
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352069
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352070
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352071
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352072
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352073
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352074
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352075
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352076
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352077
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352078
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352079
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352080
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352081
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352082
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352083
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352084
16-Mar-2026 13:06:39 DEBUG GEOparse - SAMPLE: GSM1352085
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352086
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352087
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352088
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352089
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352090
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352091
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352092
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352093
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352094
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352095
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352096
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352097
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352098
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352099
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352100
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352101
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352102
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352103
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352104
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352105
16-Mar-2026 13:06:40 DEBUG GEOparse - SAMPLE: GSM1352106
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352107
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352108
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352109
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352110
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352111
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352112
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352113
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352114
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352115
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352116
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352117
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352118
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352119
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352120
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352121
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352122
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352123
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352124
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352125
16-Mar-2026 13:06:41 DEBUG GEOparse - SAMPLE: GSM1352126
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352127
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352128
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352129
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352130
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352131
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352132
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352133
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352134
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352135
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352136
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352137
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352138
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352139
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352140
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352141
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352142
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352143
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352144
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352145
16-Mar-2026 13:06:42 DEBUG GEOparse - SAMPLE: GSM1352146
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352147
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352148
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352149
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352150
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352151
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352152
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352153
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352154
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352155
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352156
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352157
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352158
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352159
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352160
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352161
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352162
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352163
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352164
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352165
16-Mar-2026 13:06:43 DEBUG GEOparse - SAMPLE: GSM1352166
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352167
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352168
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352169
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352170
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352171
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352172
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352173
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352174
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352175
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352176
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352177
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352178
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352179
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352180
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352181
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352182
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352183
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352184
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352185
16-Mar-2026 13:06:44 DEBUG GEOparse - SAMPLE: GSM1352186
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352187
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352188
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352189
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352190
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352191
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352192
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352193
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352194
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352195
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352196
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352197
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352198
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352199
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352200
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352201
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352202
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352203
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352204
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352205
16-Mar-2026 13:06:45 DEBUG GEOparse - SAMPLE: GSM1352206
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352207
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352208
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352209
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352210
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352211
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352212
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352213
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352214
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352215
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352216
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352217
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352218
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352219
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352220
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352221
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352222
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352223
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352224
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352225
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352226
16-Mar-2026 13:06:46 DEBUG GEOparse - SAMPLE: GSM1352227
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352228
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352229
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352230
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352231
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352232
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352233
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352234
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352235
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352236
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352237
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352238
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352239
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352240
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352241
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352242
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352243
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352244
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352245
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352246
16-Mar-2026 13:06:47 DEBUG GEOparse - SAMPLE: GSM1352247
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352248
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352249
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352250
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352251
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352252
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352253
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352254
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352255
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352256
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352257
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352258
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352259
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352260
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352261
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352262
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352263
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352264
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352265
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352266
16-Mar-2026 13:06:48 DEBUG GEOparse - SAMPLE: GSM1352267
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352268
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352269
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352270
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352271
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352272
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352273
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352274
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352275
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352276
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352277
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352278
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352279
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352280
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352281
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352282
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352283
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352284
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352285
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352286
16-Mar-2026 13:06:49 DEBUG GEOparse - SAMPLE: GSM1352287
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352288
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352289
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352290
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352291
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352292
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352293
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352294
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352295
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352296
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352297
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352298
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352299
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352300
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352301
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352302
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352303
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352304
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352305
16-Mar-2026 13:06:50 DEBUG GEOparse - SAMPLE: GSM1352306
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352307
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352308
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352309
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352310
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352311
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352312
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352313
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352314
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352315
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352316
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352317
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352318
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352319
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352320
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352321
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352322
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352323
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352324
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352325
16-Mar-2026 13:06:51 DEBUG GEOparse - SAMPLE: GSM1352326
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352327
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352328
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352329
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352330
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352331
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352332
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352333
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352334
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352335
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352336
16-Mar-2026 13:06:52 DEBUG GEOparse - SAMPLE: GSM1352337

In [18]:
expr.columns = expr.columns.map(mapping)

In [19]:
print(expr.columns[:10])
print(meth.columns[:10])

Index(['100001', '100002', '100003', '100004', '100005', '100006', '100007',
       '100008', '100009', '100010'],
      dtype='object')
Index(['100001', '100002', '100003', '100004', '100005', '100006', '100007',
       '100008', '100009', '100010'],
      dtype='object')

In [20]:
common = expr.columns.intersection(meth.columns)

expr = expr[common]
meth = meth[common]

print(expr.shape)
print(meth.shape)

(47278, 1202)
(485577, 1202)

In [21]:
expr = expr.T

In [22]:
meth = meth.T

In [ ]:
#feature reduction based on variance
expr = expr.loc[:, expr.var().nlargest(5000).index]
meth = meth.loc[:, meth.var().nlargest(20000).index]

In [24]:
print(meth.shape)

(1202, 20000)

In [25]:
print(expr.shape)

(1202, 5000)

In [29]:
import numpy as np

np.save("../data/processed/expression.npy", expr.values)
np.save("../data/processed/methylation.npy", meth.values)

In [33]:
from sklearn.preprocessing import StandardScaler

expr_scaler = StandardScaler()
meth_scaler = StandardScaler()

expr_scaled = expr_scaler.fit_transform(expr)
meth_scaled = meth_scaler.fit_transform(meth)

In [34]:
import pandas as pd

expr_scaled = pd.DataFrame(expr_scaled, index=expr.index, columns=expr.columns)
meth_scaled = pd.DataFrame(meth_scaled, index=meth.index, columns=meth.columns)

In [36]:
import numpy as np

np.save("../data/processed/expression_training.npy", expr_scaled.values)
np.save("../data/processed/methylation_training.npy", meth_scaled.values)

In [37]:
expr.columns.to_series().to_csv("../data/processed/expression_features.csv")
meth.columns.to_series().to_csv("../data/processed/methylation_features.csv")

expr.index.to_series().to_csv("../data/processed/sample_ids.csv")

In [38]:
print(expr_scaled.shape)
print(meth_scaled.shape)

(1202, 5000)
(1202, 20000)